name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Current configuration:
# - python 3.9, wagtail 3.0
# - python 3.8, wagtail 2.16
# - python 3.7, django 2.15

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.9
            wagtail: wagtail>=3.0,<4.0
            latest: true
          - python: 3.8
            wagtail: wagtail>=2.16,<3.0
          - python: 3.7
            wagtail: wagtail>=2.15, <2.16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/setup.cfg"
      - run: |
          pip install coverage
          pip install "${{ matrix.wagtail }}"
      - run: |
          coverage run ./runtests.py
          coverage report
          coverage xml
      - if: ${{ matrix.latest }}
        uses: codecov/codecov-action@v2
        with:
          name: Python 3.9